# Generated by Django 3.1.3 on 2020-11-24 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('context_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('context_name', models.CharField(max_length=120, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=120, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoType',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.resource')),
            ],
        ),
        migrations.CreateModel(
            name='TodoStatus',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, help_text='Short description of the todo item ...', max_length=200)),
                ('effort_type', models.CharField(blank=True, choices=[('H', 'Hour(s)'), ('D', 'Day(s)'), ('M', 'Month(s)')], max_length=1, null=True)),
                ('effort', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_user', to='todo.resource')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to='todo.resource')),
                ('context_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.context')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='todo.todostatus')),
                ('todo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.todotype')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_group_list', models.BooleanField(default=False)),
                ('can_edit_group_list', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
